### ISSUE TITLE
Maps with maptools

### ISSUE THREAD

**Issue by johalnes** [fpechon/SummerSchool#1]
It seems like a lot of functions is deprecated in latest maptools and qqplot(fortify). It seems like sf with ggplot works better

`library(sf)
library(dplyr)
library(ggplot2)

area <- read_sf("Maps/FRA_adm2.shp")  # From http://www.diva-gis.org/gData

Region.summary$id = as.numeric(sapply(Region.summary$Region, substr, 2, 3))
area.points = area.points %>% left_join(Region.summary, by=c("ID_2"='id'))

ggplot(area.points[6]) + ggtitle("Observed Claim Frequencies") + 
  geom_sf(data= area.points[6], aes(fill = area.points$Obs.Claim.Frequency)) +
  scale_fill_gradient(low = "yellow", high = "red", name = "Obs. Claim Freq.", limits = c(0.061, 0.085)) + 
  xlab("Longitude") + 
  ylab("Latitude")`

**Comment by fpechon** [comment]
Thanks for the comment.
Indeed, I changed the code a bit last Monday. I used the readOGR package instead.
